version: "3.7"

services:
    db:
     image: mysql:5.7
     environment:
        MYSQL_ROOT_PASSWORD: "(sua senha)"
        MYSQL_DATABASE: "desafio5"
     ports:
      - "3306:3306"
     volumes:
      - /desafios/desafio5/volume:/var/lib/mysql

     networks:
      - minha-rede

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        MYSQL_ROOT_PASSWORD: "(sua senha)"
      ports:
        - "8080:80"
      volumes:
        - /desafios/desafio5/admin/upload.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini

      networks:
        - minha-rede

networks:
   minha-rede:
     driver: bridge

